spring.application.name=transport-service
server.port=8087

spring.datasource.url=jdbc:postgresql://ep-billowing-cloud-an08sm8n-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_7BGr5vzaqbpw&sslmode=require&channelBinding=require
jwt.secret=d72bd332afea8b3b5c95d0335b1b071bc25683b7aa6111762c750a8ae1afec9b

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.max-http-request-header-size=65536
eureka.instance.prefer-ip-address=true