spring.application.name=camera-service
server.port=8082

spring.datasource.url=${HOTEL_SERVICE_DB_URL}
jwt.secret=${JWT_SECRET}

server.max-http-request-header-size=65536
eureka.instance.prefer-ip-address=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.data.web.pageable.serialization-mode=via-dto