spring.application.name=discovery-server
server.port=8761

eureka.instance.hostname=localhost
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.server.enable-replicated-request-compression=false
eureka.server.renewal-percent-threshold=0.49
server.max-http-request-header-size=65536