# Bellow here is the .envs are going to be.
# Also you need to modify AppConfig file in order to access it from the code.

app.db-url=ud_url_goes_here_like_this
app.jwt-secret=a69co332pfea8b3bb7z5d0375b1b071bc25683b7aa6842762c750a8ae1aqwe2h