spring.application.name=review-service

server.port=8069

spring.datasource.url=${REVIEW_SERVICE_DB_URL}
jwt.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.max-http-request-header-size=65536
eureka.instance.prefer-ip-address=true