spring.application.name=review-service
server.port=8069

# Neon Database Connection
spring.datasource.url=jdbc:postgresql://ep-mute-base-adcqxg7w-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_PqQ72xcKSukj

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Settings
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/